In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type-a

TypeError: unsupported operand type(s) for -: 'type' and 'int'

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [7]:
a.ndim

1

In [10]:
a.size

3

In [9]:
a.add(2)

AttributeError: 'numpy.ndarray' object has no attribute 'add'

In [11]:
a.shape

(3,)

In [19]:
b = np.array([[1.3, 1.2, 5.2], [2.5, 2.3, 3.6], [2.5, 56.2, 2.1]])

In [13]:
b

array([[ 1.3,  1.2,  5.2],
       [ 2.5,  2.3,  3.6],
       [ 2.5, 56.2,  2. ]])

In [14]:
print(b)

[[ 1.3  1.2  5.2]
 [ 2.5  2.3  3.6]
 [ 2.5 56.2  2. ]]


In [15]:
b.dtype

dtype('float64')

In [16]:
b.dim

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [20]:
b.ndim

2

In [21]:
b.ndim

2

In [22]:
b

array([[ 1.3,  1.2,  5.2],
       [ 2.5,  2.3,  3.6],
       [ 2.5, 56.2,  2.1]])

In [23]:
print(b)

[[ 1.3  1.2  5.2]
 [ 2.5  2.3  3.6]
 [ 2.5 56.2  2.1]]


In [24]:
b.dtype

dtype('float64')

In [25]:
b.itemsize

8

In [26]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [27]:
import pandas as pd